name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          

      - name: Git config
        run: |
          git config --global user.name "cd-user@my-app.com"
          git config --global user.email "cd-user"


      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
    
      - name: Install
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to production
        run: npm run deploy -- -r git@github.com:NoeliaMM/my-portfolio-gh-pages-auto.git        

      - name: Notify deployment success
        run: echo "Deployment successful!"
      